<?php
/**
 * Intro!
 *
 * @author Thomas Thune Hansen <tth@bellcom.dk>
 * @copyright bellcom open source aps
 */

/*
 * Implements hook_menu()
 */
function menu_bar_menu(){
  $items = array();

  $items['admin/config/user-interface/menu_bar'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('menu_bar_admin_form'),
    'access arguments' => array('administer site configuration'),
    'title' => t('Menu bar settings'),
  );

  return $items;
}

function menu_bar_admin_form(){
  $form = array();

  $menu_bar_menus = variable_get('menu_bar_panel', FALSE);

  $panels = panels_mini_load_all();

  $options = array('<none>' => 'None');

  foreach($panels as $panel){
    if(is_object($panel)){
      $options[$panel->name] = $panel->admin_title;
    }
  }

  $form['menu_bar_panel'] = array(
    '#title' => t('Select minipanel'),
    '#type' => 'select',
    '#options' => $options,
    '#default_value' => variable_get('menu_bar_panel', '<none>'),
  );

  $form['menu_bar_narrow_width'] = array(
    '#title' => t('Narrow width'),
    '#description' => t('Enter the width the menubar should have when narrow'),
    '#type' => 'textfield',
    '#default_value' => variable_get('menu_bar_narrow_width', 55),
  );

  $form['menu_bar_wide_width'] = array(
    '#title' => t('Wide width'),
    '#description' => t('Enter the width the menubar should have when wide(expanded)'),
    '#type' => 'textfield',
    '#default_value' => variable_get('menu_bar_wide_width', 160),
  );

  $form['menu_bar_hide_no_login'] = array(
    '#title' => t('Hide the menubar if the user is not logged in'),
    '#type' => 'checkbox',
    '#default_value' => variable_get('menu_bar_hide_no_login', TRUE),
  );
  return system_settings_form($form);
}

/*
 * Implements hook_init()
 */
function menu_bar_init(){
  global $user;
  $hide_no_login = variable_get('menu_bar_hide_no_login', TRUE);

  if(!$user->uid && $hide_no_login){
    return;
  }

  // Load panel id
  $menu_bar_panel = variable_get('menu_bar_panel', '<none>');

  // check if we should add all the stuff
  if($menu_bar_panel !== '<none>' && !path_is_admin(current_path())){
    drupal_add_js(drupal_get_path('module', 'menu_bar') . '/js/menu_bar.js');
    drupal_add_css(drupal_get_path('module', 'menu_bar') . '/css/menu_bar.css');

    // Add admin settings
    $settings = array(
      'narrow_width' => variable_get('menu_bar_narrow_width', 55),
      'wide_width' => variable_get('menu_bar_wide_width', 160),
    );

    drupal_add_js(array('menu_bar' => $settings), 'setting');
  }
}

/*
 * Implements hook_page_alter
 */
function menu_bar_page_alter(&$page){
  global $user;
  $hide_no_login = variable_get('menu_bar_hide_no_login', TRUE);


  if(!$user->uid && $hide_no_login){
    return;
  }

  $block = module_invoke('panels_mini', 'block_view', variable_get('menu_bar_panel'));
  
  $ignore_uris = array(
    '/media/*',
  );

  if(!empty($block) && !path_is_admin(current_path()) && !drupal_match_path(request_uri(), implode("\n", $ignore_uris))){
    $menus = $block['content'];

    $page['page_bottom']['menu_bar']['#markup'] = '<div class="menu-bar-menu narrow"><div class="menu-bar-inner"><div class="js-menu-bar-toggle"></div>'.$menus.'</div></div>';
  }
}
